branches:
  only:
  - master

secure: "gg7XxI9E0NMccnrTX86Y3LIg1DDTGPkEcfir4zG0U92GAxBXsWR51NKzZZOEJGRYH1hlXfOvWdaQKdgHwODWYS/hb3pM+sKYwA+BMSZc/bP3sm1VkX5nGBZHfrMRxcX+fDtOSpgnyUWXOq3HVUIRWxmqswQBK/5SqoQENG0vFhQNKGVPaayY+/iQCDL/6rWeUIx1a/TDhh+hMCrikXLxf9m/istsbRMW/7LcrkKMwu0WsNrUxGSvlpoXA1NyYJNtgBc2yx1CGIRAZq73fjjI/JO22xZQL3kvbNnim2cJJBaKjYV4TYas5FDrBBfqd49He0ayq1v5UVtST1gKjRxikHHbgwGk6bIxueCk0QhTl0a2irLYgjNAfjaVcT4CFGpc86xTGQzmgXLA5kIOnbJw5IrrXkzcC3xmlGcXkuCXAWJ7s3xjlehc6D1ie4h12vnbq131eQJrErGr/2sldCsBnNz+FHdPBVzdaDBP36c9TQazvL9bb57GVQuAK1pU2gQ1DK7YQiiYjk4guw1EqmGzjhAydGpuMLBy3VXUbPnXMXbTtUe/HwTfIZP99dy5hEaZeX0MfegBwFVWvXx1HW0KkXDKIEIVs17p4lyzGt8O7xXvfrUIn95QaUtmP8ab3QgsIEdg2dt40d4ZUXanqQ0gLWtmoNzfdvfIsf0c8uKZX90="

language: python

python:
  - 3.4

install:
  - pip install -r requirements.txt

script:
  - make html

notifications:
  email: false

after_success: ./deploy.sh
